---
deployment:
  tasks:
    - export DEPLOYPATH=/home/stmb5393/public_html/digilib.stmiklombok.ac.id/
    - export PATHROOT=/home/stmb5393/sim-skripsi/
    - /bin/cp -R public/* $DEPLOYPATH
    - /bin/cp -R * $PATHROOT
